# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05c6246967c5e6a3091c6e13068da4457b97f0de1cbad2253f222f63db1153ddbe1a297c8a10c9dbe3a630c53a2280b684074e50525160cb3a7061adfafad389

test:
  secret_key_base: e770748488bfcdbd5439345ae4ff8c4ef5084faa3702fe8e79f02ecc6a809016c1b893b54efa66c03fcd660036876182c5a79628f078c28301371104cacf8640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
